export interface AgentDetail {
  agent_id: string
  name: string
  status: 'active' | 'idle' | 'error'
  capabilities: string[]
  active_tasks: number
  tasks_completed: number
  tasks_failed: number
  cost_today: number
  last_seen: string
  error_message?: string
}

export interface SystemMetrics {
  timestamp: string
  agents: {
    total: number
    active: number
    utilization: number
    details: AgentDetail[]
  }
  tasks: {
    completed: number
    failed: number
    success_rate: number
  }
  queues: {
    total_depth: number
    by_capability: Record<string, number>
    dead_letter_queue: number
  }
  costs: {
    today: number
    month: number
    by_model: Record<string, number>
  }
}

export interface Alert {
  alert_id: string
  severity: 'critical' | 'warning' | 'info'
  message: string
  source: string
  created_at: string
  acknowledged: boolean
  metadata?: Record<string, any>
}

export interface AlertStats {
  active: {
    total: number
    critical: number
    warning: number
    info: number
  }
  last_24h: {
    total: number
    critical: number
    warning: number
    info: number
  }
}

export interface TimeSeriesDataPoint {
  timestamp: string
  value: number
}

export interface QueueMetrics {
  total_depth: number
  by_capability: Record<string, number>
  dead_letter_queue: number
}

// Workflow Designer Types
export type NodeType = 'supervisor' | 'worker' | 'tool' | 'trigger' | 'integration' | 'condition' | 'memory' | 'knowledge' | 'webhook' | 'hitl' | 'print'
export type NodeStatus = 'idle' | 'running' | 'success' | 'error' | 'pending'
export type TriggerType = 'webhook' | 'cron' | 'manual' | 'event'
export type WebhookAuthType = 'none' | 'secret' | 'hmac' | 'oauth2' | 'basic_auth' | 'bearer' | 'api-key' | 'basic'
export type HITLApprovalType = 'any' | 'all' | 'majority'
export type HITLNotifyChannel = 'email' | 'slack' | 'sms'
export type IntegrationType = 'slack' | 'discord' | 'gmail' | 'stripe' | 'github' | 'sendgrid' | 'twilio' | 'aws_s3' | 'zendesk' | 'hubspot' | 'salesforce' | 'notion' | 'airtable' | 'mailchimp' | 'google_sheets' | 'custom'

export interface TriggerConfig {
  triggerType?: TriggerType
  webhookUrl?: string
  cronExpression?: string
  eventName?: string
  eventSource?: string
}

export interface IntegrationConfig {
  integrationType?: IntegrationType
  action?: string
  credentials?: string // Reference to stored credentials
  parameters?: Record<string, any>
  isConnected?: boolean // Whether the integration has valid credentials configured
}

export interface ConditionConfig {
  expression?: string
  trueLabel?: string
  falseLabel?: string
}

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH'
export type AuthType = 'none' | 'api_key' | 'bearer' | 'basic' | 'oauth2'

export interface ToolConfig {
  url?: string
  method?: HttpMethod
  headers?: Record<string, string>
  body?: string // JSON template
  auth?: {
    type: AuthType
    apiKey?: string // For api_key type
    headerName?: string // For api_key type (e.g., 'X-API-Key')
    bearerToken?: string // For bearer type
    username?: string // For basic auth
    password?: string // For basic auth
  }
  timeout?: number // milliseconds
  retry?: {
    maxRetries: number
    backoffMs: number
  }
  responseMapping?: string // JSONPath or template to extract response data
}

export type MemoryOperation = 'store' | 'query' | 'delete'

export interface MemoryConfig {
  operation?: MemoryOperation
  providerId?: string // Reference to configured memory provider
  namespace?: string
  content?: string // For store operation (supports {{templates}})
  query?: string // For query operation (supports {{templates}})
  limit?: number // For query operation
  filters?: Record<string, any>
  metadata?: Record<string, any>
}

export interface KnowledgeConfig {
  connectorId?: string // Reference to configured RAG connector
  query?: string // Search query (supports {{templates}})
  limit?: number
  filters?: Record<string, any>
  rerank?: boolean
  minScore?: number
}

export interface WebhookConfig {
  webhookUrl?: string // Auto-generated by platform
  authentication?: {
    type?: WebhookAuthType
    secret?: string
    hmacHeader?: string
    algorithm?: 'sha256' | 'sha1'
    username?: string
    password?: string
    keyName?: string
    keyValue?: string
    token?: string
  }
  method?: 'POST' | 'GET'
  contentType?: 'application/json' | 'application/x-www-form-urlencoded'
  payloadMapping?: Record<string, string> // Extract fields from payload
  conditions?: Array<{
    field: string
    operator: 'equals' | 'contains' | 'regex'
    value: string
  }>
  responseStatus?: number
  responseBody?: string
}

export interface HITLConfig {
  approvers?: string[] // Email addresses or user IDs
  approvalType?: HITLApprovalType
  timeout?: number // Minutes until auto-action
  timeoutAction?: 'reject' | 'approve' | 'retry'
  notifyVia?: HITLNotifyChannel[]
  emailTemplate?: string
  slackChannel?: string
  title?: string
  description?: string
  contextData?: Record<string, any>
  approveLabel?: string
  rejectLabel?: string
  customActions?: Array<{
    label: string
    value: string
  }>
}

export interface PrintConfig {
  label?: string // Label to display in the Execution Log
  message?: string // The message to print (supports {{variable}} templates)
  includeTimestamp?: boolean // Whether to include timestamp
  logLevel?: 'info' | 'debug' | 'warning' | 'error'
}

export interface AgentNodeData {
  label: string
  type: NodeType
  agentId?: string
  capabilities?: string[]
  // LLM Model Selection (NEW)
  modelSelection?: 'auto' | 'cost_optimized' | 'latency_optimized' | 'quality_first' | string // 'auto' or strategy type or specific model
  routingStrategy?: string | null // Override strategy for this agent
  llmModel?: string // Deprecated: only used if modelSelection is a specific model
  tools?: string[]
  config?: Record<string, any>
  status?: NodeStatus
  cost?: number
  executionTime?: number
  error?: string
  // Runtime routing info (populated during execution)
  actualProvider?: string
  actualModel?: string
  routingReason?: string
  // Prompt-related
  prompt?: string // Manual prompt text
  promptSlug?: string // Prompt from registry
  promptVersion?: string // Version of registry prompt
  promptVariables?: Record<string, string> // Variable mappings for registry prompt
  // Trigger-specific
  triggerConfig?: TriggerConfig
  // Integration-specific
  integrationConfig?: IntegrationConfig
  // Condition-specific
  conditionConfig?: ConditionConfig
  // Tool-specific
  toolConfig?: ToolConfig
  // Memory-specific
  memoryConfig?: MemoryConfig
  // Knowledge-specific
  knowledgeConfig?: KnowledgeConfig
  // Webhook-specific
  webhookConfig?: WebhookConfig
  // HITL-specific
  hitlConfig?: HITLConfig
  // Print-specific
  printConfig?: PrintConfig
}

export interface WorkflowNode {
  id: string
  type: string
  position: { x: number; y: number }
  data: AgentNodeData
}

export interface WorkflowEdge {
  id: string
  source: string
  target: string
  label?: string
  type?: 'default' | 'smoothstep' | 'step' | 'straight'
  animated?: boolean
  data?: {
    messageFormat?: string
    retryPolicy?: {
      maxRetries: number
      backoffMs: number
    }
    condition?: string
  }
}

export interface Workflow {
  id: string
  name: string
  description?: string
  tags?: string[]
  nodes: WorkflowNode[]
  edges: WorkflowEdge[]
  createdAt: string
  updatedAt: string
  createdBy?: string
  version?: number
  isTemplate?: boolean
  metadata?: {
    totalCost?: number
    executionCount?: number
    lastExecuted?: string
    averageExecutionTime?: number
  }
}

export interface WorkflowExecution {
  id: string
  workflowId: string
  status: 'pending' | 'running' | 'success' | 'failed' | 'cancelled'
  startTime: string
  endTime?: string
  totalCost: number
  nodeExecutions: {
    nodeId: string
    status: NodeStatus
    startTime: string
    endTime?: string
    cost: number
    error?: string
    output?: any
  }[]
}

export interface WorkflowTemplate {
  id: string
  name: string
  description: string
  category: string
  thumbnail?: string
  nodes: WorkflowNode[]
  edges: WorkflowEdge[]
  usageCount?: number
}

// Task Management Types
export type TaskStatus = 'pending' | 'queued' | 'running' | 'completed' | 'failed' | 'cancelled'
export type TaskPriority = 'low' | 'normal' | 'high' | 'critical'

export interface Task {
  task_id: string
  capability: string
  status: TaskStatus
  priority?: TaskPriority
  assigned_agent_id?: string
  input: Record<string, any>
  output?: Record<string, any>
  error?: string
  created_at: string
  started_at?: string
  completed_at?: string
  retry_count?: number
  cost?: number
}

export interface TaskSubmission {
  capability: string
  input_data: Record<string, any>
  priority?: TaskPriority
  timeout_seconds?: number
  max_retries?: number
}

export interface TaskResponse {
  task_id: string
  status: string
  capability: string
}

export interface TaskFilters {
  status?: TaskStatus
  capability?: string
  agent_id?: string
}
